name: Build & Deploy to EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build with Maven
        run: |
          if [ -f "./mvnw" ]; then
            chmod +x mvnw
            ./mvnw -DskipTests package
          else
            sudo apt-get update -y
            sudo apt-get install -y maven
            mvn -DskipTests package
          fi

      - name: Copy JAR to EC2 (via SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          port: ${{ secrets.EC2_SSH_PORT }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/*.jar"
          target: "/home/ubuntu/upload/"
          strip_components: 1
          overwrite: true

      - name: Deploy on EC2 (restart app)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          port: ${{ secrets.EC2_SSH_PORT }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            mv -f /home/ubuntu/upload/*.jar /home/ubuntu/upload/budgetcaddie.jar
            bash /home/ubuntu/deploy.sh
